version: '3'
services:
  # Web server
  server:
    image: server
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/certs:/etc/nginx/certs
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network

  # Web app front
  nxt-node-sample:
    image: nxt-node-sample
    container_name: nxt-node-sample
    restart: unless-stopped
    build:
      context: ./nxt-node-sample
      dockerfile: Dockerfile.dev
    volumes:
      - ./nxt-node-sample:/usr/src/nxt-node-sample:cached
      - ./nxt-backend:/usr/src/nxt-node-sample/node_modules/nxt-backend:cached
      - ./nxt-shared:/usr/src/nxt-node-sample/node_modules/nxt-shared:cached
    ports:
      - '8080:8080'
    networks:
      - app-network
    depends_on:
      - nxt-mongo-db
      - s3

  # Web app front
  nxt-angular-sample:
    image: nxt-angular-sample
    container_name: nxt-angular-sample
    restart: unless-stopped
    build:
      context: ./nxt-angular-sample
      dockerfile: Dockerfile.dev
    volumes:
      - ./nxt-angular-sample:/usr/src/nxt-angular-sample:cached
      - ./nxt-shared:/usr/src/nxt-angular-sample/node_modules/nxt-shared:cached
    ports:
      - '4200:4200'
    networks:
      - app-network
  ### SERVICES SPOT (don't touch)

  # Mongo DB
  nxt-mongo-db:
    image: mongo:4.2
    container_name: nxt-mongo-db
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: nxt-microservices
      MONGO_INITDB_ROOT_PASSWORD: nxt-microservices
      MONGO_INITDB_DATABASE: nxt-microservices
    volumes:
      - ./mongo_data:/data/db:cached
    ports:
      - '27017:27017'
    networks:
      - app-network

  # AWS S3 compatible server https://min.io
  s3:
    image: 'minio/minio:latest'
    container_name: nxt-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ./s3_data:/data:cached
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
