Deploy nxt-node-sample to staging:
  image: ubuntu:20.04
  only:
    refs:
      - develop
    changes:
      - nxt-node-sample/**/*
      - nxt-backend/**/*
      - nxt-shared/**/*
  dependencies:
    - Generate nxt-node-sample zip for staging
  stage: deploy
  before_script:
    - cd nxt-node-sample
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${STAGING_SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$STAGING_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "rm -rf /home/${STAGING_SERVER_USER}/nxt-node-sample"
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "mkdir /home/${STAGING_SERVER_USER}/nxt-node-sample"
    - scp build.zip ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST}:/home/${STAGING_SERVER_USER}/nxt-node-sample
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "unzip /home/${STAGING_SERVER_USER}/nxt-node-sample/build.zip -d /home/${STAGING_SERVER_USER}/nxt-node-sample"
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "docker container rm --force nxt-node-sample || true"
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "docker build /home/${STAGING_SERVER_USER}/nxt-node-sample -t nxt-node-sample"
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "docker run --restart=on-failure -p 8080:8080 -d --name nxt-node-sample nxt-node-sample"
    - ssh ${STAGING_SERVER_USER}@${STAGING_SERVER_HOST} "rm -rf /home/${STAGING_SERVER_USER}/nxt-node-sample"
