# Zip generation
Generate wb-user zip for staging:
  image: ubuntu:20.04
  only:
    refs:
      - develop
    changes:
      - wb-user/**/*
      - nxt-backend/**/*
      - nxt-shared/**/*
  dependencies:
    - Build wb-user for staging
    - Prepare wb-user dockerfile for staging
  stage: zip
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
  script:
    - mkdir -p tmp/wb-user
    - mkdir -p tmp/nxt-backend
    - mkdir -p tmp/nxt-shared
    - cp wb-user/Dockerfile tmp/
    - cp wb-user/package.json tmp/wb-user/
    - cp wb-user/package-lock.json tmp/wb-user/
    - cp -R wb-user/dist/ tmp/wb-user/dist/
    - cp nxt-backend/package.json tmp/nxt-backend/
    - cp nxt-backend/package-lock.json tmp/nxt-backend/
    - cp -R nxt-backend/dist/ tmp/nxt-backend/dist/
    - cp -R nxt-shared/dist/ tmp/nxt-shared/dist/
    - cp nxt-shared/package.json tmp/nxt-shared/
    - cp nxt-shared/package-lock.json tmp/nxt-shared/
    - cd tmp
    - zip -r build.zip Dockerfile wb-user/ nxt-backend/ nxt-shared/
    - mv build.zip ../wb-user/build.zip
  artifacts:
    paths:
      - wb-user/build.zip
    expire_in: 2 weeks

Generate wb-user zip for preprod:
  image: ubuntu:20.04
  only:
    refs:
      - master
    changes:
      - wb-user/**/*
      - nxt-backend/**/*
      - nxt-shared/**/*
  dependencies:
    - Build wb-user for preprod
    - Prepare wb-user dockerfile for preprod
  stage: zip
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
  script:
    - mkdir -p tmp/wb-user
    - mkdir -p tmp/nxt-backend
    - mkdir -p tmp/nxt-shared
    - cp wb-user/Dockerfile tmp/
    - cp wb-user/package.json tmp/wb-user/
    - cp wb-user/package-lock.json tmp/wb-user/
    - cp -R wb-user/dist/ tmp/wb-user/dist/
    - cp nxt-backend/package.json tmp/nxt-backend/
    - cp nxt-backend/package-lock.json tmp/nxt-backend/
    - cp -R nxt-backend/dist/ tmp/nxt-backend/dist/
    - cp -R nxt-shared/dist/ tmp/nxt-shared/dist/
    - cp nxt-shared/package.json tmp/nxt-shared/
    - cp nxt-shared/package-lock.json tmp/nxt-shared/
    - cd tmp
    - zip -r build.zip Dockerfile wb-user/ nxt-backend/ nxt-shared/
    - mv build.zip ../wb-user/build.zip
  artifacts:
    paths:
      - wb-user/build.zip
    expire_in: 2 weeks

Generate wb-user zip for production:
  image: ubuntu:20.04
  only:
    refs:
      - tags
    changes:
      - wb-user/**/*
      - nxt-backend/**/*
      - nxt-shared/**/*
  dependencies:
    - Build wb-user for production
    - Prepare wb-user dockerfile for production
  stage: zip
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
  script:
    - mkdir -p tmp/wb-user
    - mkdir -p tmp/nxt-backend
    - mkdir -p tmp/nxt-shared
    - cp wb-user/Dockerfile tmp/
    - cp wb-user/package.json tmp/wb-user/
    - cp wb-user/package-lock.json tmp/wb-user/
    - cp -R wb-user/dist/ tmp/wb-user/dist/
    - cp nxt-backend/package.json tmp/nxt-backend/
    - cp nxt-backend/package-lock.json tmp/nxt-backend/
    - cp -R nxt-backend/dist/ tmp/nxt-backend/dist/
    - cp -R nxt-shared/dist/ tmp/nxt-shared/dist/
    - cp nxt-shared/package.json tmp/nxt-shared/
    - cp nxt-shared/package-lock.json tmp/nxt-shared/
    - cd tmp
    - zip -r build.zip Dockerfile wb-user/ nxt-backend/ nxt-shared/
    - mv build.zip ../wb-user/build.zip
  artifacts:
    paths:
      - wb-user/build.zip
    expire_in: 2 weeks
